# Generated by Django 5.1.1 on 2026-08-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_developer',
            field=models.BooleanField(default=False, verbose_name='Разработчик'),
        ),
    ]
