# Generated by Django 5.1.1 on 2026-08-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_newsuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
