# Generated by Django 5.1.1 on 2026-09-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_newsuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsuser',
            name='is_publish_on_top',
            field=models.BooleanField(default=False, verbose_name='Публикация на главной странице'),
        ),
    ]
