# Generated by Django 5.1.1 on 2026-10-06 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_newsuser_is_publish_on_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveIntegerField(default=3600, help_text='Как часто бот публикует новость (в секундах).', verbose_name='Интервал публикации (сек)')),
                ('last_post_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней публикации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_user', to=settings.AUTH_USER_MODEL, verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
        migrations.CreateModel(
            name='BotNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(max_length=150, verbose_name='Название новости.')),
                ('text_news', models.TextField(max_length=450, verbose_name='Описание новости.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('is_publish_on_top', models.BooleanField(default=True, verbose_name='Публикация на главной странице')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_news', to='api.botuser', verbose_name='Новости бота')),
            ],
            options={
                'verbose_name': 'Новости бота',
                'verbose_name_plural': 'Новости бота',
                'ordering': ('created_at',),
            },
        ),
    ]
