version: '3'

volumes:
  static_volume:
  media:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    build: ./backend/
    env_file: .env
    command: >
      sh -c "python manage.py migrate --noinput &&
            python manage.py collectstatic --noinput &&
            python manage.py load_data &&
            gunicorn --bind 0.0.0.0:8000 foodgram.wsgi"
    volumes:
      - ./data:/app/data
      - static_volume:/backend_static
      - media:/app/media

  frontend:
    depends_on:
      - backend
    env_file: .env
    build:
      context: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    build: ./infra/
    env_file: .env
    volumes:
      - static_volume:/usr/share/nginx/html/
      - media:/usr/share/nginx/html/media
    ports:
      - 6000:80